import json
import os
from typing import Dict, Any, Optional

def get_care_pathways() -> Dict[str, Any]:
    filepath = os.path.join(os.path.dirname(__file__), "care_pathways.json")
    try:
        with open(filepath, "r") as f:
            data = json.load(f)
            return data.get("care_pathways", {})
    except Exception as e:
        print(f"Error loading care_pathways.json: {e}")
        return {}

def resolve_ctas(action_steps: Dict[str, Any], risk_level: str = "LOW", context: str = "") -> Dict[str, Any]:
    """
    Takes the structured action_steps block generated by the LLM (which includes 
    title, title_emphasis, description, and selected_pathway) and injects the 
    appropriate CTA buttons from care_pathways.json.
    """
    if not isinstance(action_steps, dict):
        # Fallback if LLM failed to output JSON
        return {
            "title": "Action Required",
            "description": str(action_steps),
            "primary_cta": {
                "label": "Review my metrics",
                "action": "VIEW_METRICS",
                "icon": "activity"
            }
        }

    pathway_key = action_steps.get("selected_pathway", "level_7_wellness_maintenance")
    pathways = get_care_pathways()
    
    # Get the selected pathway, fallback to wellness maintenance if not found
    selected = pathways.get(pathway_key, pathways.get("level_7_wellness_maintenance", {}))
    
    # We must deep copy to avoid mutating the original care_pathways in memory
    import copy
    primary_cta = copy.deepcopy(selected.get("primary_cta"))
    secondary_cta = copy.deepcopy(selected.get("secondary_cta"))
    
    # Ultimate fallback
    if not primary_cta:
        primary_cta = {
            "label": "Review my metrics",
            "action": "VIEW_METRICS",
            "icon": "activity"
        }

    # Inject dynamic context if provided (crucial for Coach Chat)
    if context:
        if primary_cta:
            primary_cta["context"] = context
        if secondary_cta:
            secondary_cta["context"] = context

    # Inject into the action_steps dictionary
    action_steps["primary_cta"] = primary_cta
    if secondary_cta:
        action_steps["secondary_cta"] = secondary_cta
        
    # Remove selected_pathway so we don't send it to the frontend unnecessarily
    action_steps.pop("selected_pathway", None)
    # Also pop intent_key if it accidentally generated it
    action_steps.pop("intent_key", None)
        
    return action_steps
