import json
import os
import copy
from datetime import datetime, timezone, timedelta
from typing import Dict, Any, Optional

def get_care_pathways() -> Dict[str, Any]:
    filepath = os.path.join(os.path.dirname(__file__), "care_pathways.json")
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            data = json.load(f)
            return data
    except Exception as e:
        print(f"Error loading care_pathways.json: {e}")
        return {"pathways": {}, "legacy_aliases": {}}

def check_temporal_escalation(
    patient_id: str,
    domain: str,
    supabase_client: Any = None
) -> bool:
    """
    Checks if an alert for the same clinical domain has been active for >= 48 hours.
    If so, returns True to indicate that Level 1 should be promoted to Level 2.
    """
    if not patient_id:
        return False
        
    try:
        if supabase_client is None:
            from app.config import settings
            from supabase import create_client
            supabase_client = create_client(settings.SUPABASE_URL, settings.SUPABASE_SERVICE_ROLE_KEY)
            
        forty_eight_hours_ago = (datetime.now(timezone.utc) - timedelta(hours=48)).isoformat()
        
        # 1. Check active_clinical_insights for persistent unresolved alerts
        res = supabase_client.table("active_clinical_insights") \
            .select("id, created_at, category, rule_id") \
            .eq("patient_id", patient_id) \
            .eq("status", "active") \
            .lte("created_at", forty_eight_hours_ago) \
            .limit(5) \
            .execute()
            
        if res.data and len(res.data) > 0:
            # Map domain keywords to category/rule_id
            domain_keywords = {
                "occult_infection_sepsis": ["fever", "infection", "temp", "general"],
                "respiratory_hypoxemia_osa": ["respiratory", "spo2", "apnea", "snore", "cough"],
                "cardiorenal_fluid_balance": ["weight", "renal", "kidney", "fluid", "decompensation"],
                "sarcopenia_fall_prevention": ["mobility", "cadence", "fall", "sarcopenia", "frailty"],
                "cardio_autonomic_strain": ["cardiac", "heart", "bp", "hypertension", "tachycardia"],
                "sleep_metabolic_dysregulation": ["sleep", "metabolic", "glucose", "diabetes", "hba1c"],
                "geriatric_polypharmacy": ["medication", "meds", "drug", "interaction"],
            }
            keywords = domain_keywords.get(domain, [domain])
            for alert in res.data:
                alert_text = f"{alert.get('category', '')} {alert.get('rule_id', '')}".lower()
                if any(kw in alert_text for kw in keywords):
                    return True

        # 2. Check prior nudge_alerts for persistent similar domain nudges created >= 48h ago
        nudge_res = supabase_client.table("nudge_alerts") \
            .select("id, created_at, action_steps") \
            .eq("patient_id", patient_id) \
            .lte("created_at", forty_eight_hours_ago) \
            .order("created_at", desc=True) \
            .limit(3) \
            .execute()

        if nudge_res.data:
            for n in nudge_res.data:
                steps = n.get("action_steps")
                if isinstance(steps, dict):
                    prior_domain = steps.get("clinical_domain") or steps.get("selected_pathway")
                    if prior_domain == domain:
                        return True
                        
    except Exception as e:
        print(f"[TemporalEscalation] Check skipped due to error: {e}")
        
    return False

def resolve_ctas(
    action_steps: Dict[str, Any],
    risk_level: str = "LOW",
    context: str = "",
    patient_id: Optional[str] = None,
    supabase_client: Any = None
) -> Dict[str, Any]:
    """
    Takes the structured action_steps block generated by the LLM and injects:
    1. Domain-specific primary & secondary CTA buttons.
    2. Dynamic Bedside Caregiver Checklist.
    3. Deterministic Safety Clamping (HIGH risk -> Level 3 Emergency).
    4. Longitudinal Temporal Escalation (Active >48h -> Promotes Level 1 to Level 2).
    """
    if not isinstance(action_steps, dict):
        # Fallback if LLM failed to output JSON
        return {
            "title": "Action Required",
            "description": str(action_steps),
            "caregiver_checklist": [
                "Take a quiet moment to sit down, rest, and drink a glass of water",
                "Review today's vitals on your dashboard"
            ],
            "primary_cta": {
                "label": "Review my metrics",
                "action": "VIEW_METRICS",
                "icon": "activity"
            },
            "secondary_cta": {
                "label": "Chat with Health Coach",
                "action": "START_COACH_CHAT",
                "icon": "message-circle"
            },
            "escalation_tier": "level_1_bedside_triage"
        }

    catalog = get_care_pathways()
    pathways = catalog.get("pathways", {})
    legacy_aliases = catalog.get("legacy_aliases", {})

    # 1. Identify Domain
    raw_domain = (
        action_steps.get("selected_domain")
        or action_steps.get("selected_pathway")
        or action_steps.get("domain")
        or "wellness_vitality_reinforcement"
    )
    raw_level = (
        action_steps.get("escalation_level")
        or action_steps.get("level")
    )

    # Resolve legacy aliases (e.g. 'level_1_emergency_dispatch' -> domain + level)
    if raw_domain in legacy_aliases:
        alias = legacy_aliases[raw_domain]
        selected_domain = alias.get("domain", "wellness_vitality_reinforcement")
        if not raw_level:
            raw_level = alias.get("level")
    else:
        selected_domain = raw_domain

    if selected_domain not in pathways:
        selected_domain = "wellness_vitality_reinforcement"

    domain_data = pathways.get(selected_domain, pathways.get("wellness_vitality_reinforcement", {}))
    escalation_levels = domain_data.get("escalation_levels", {})

    # 2. Determine Escalation Tier with Safety Clamping
    norm_risk = (risk_level or "LOW").upper()
    default_tier_by_risk = {
        "HIGH": "level_3_acute_emergency",
        "MEDIUM": "level_2_diagnostic_investigation",
        "LOW": "level_1_bedside_triage"
    }

    # SAFETY CLAMP: A clinical HIGH risk level can NEVER be downgraded to Level 1
    if norm_risk == "HIGH":
        resolved_tier = "level_3_acute_emergency"
    elif raw_level in escalation_levels:
        resolved_tier = raw_level
    else:
        resolved_tier = default_tier_by_risk.get(norm_risk, "level_1_bedside_triage")

    # 3. Longitudinal Temporal Escalation Check
    # If currently at Level 1, check if the underlying condition has persisted for >= 48 hours
    if resolved_tier == "level_1_bedside_triage" and patient_id:
        is_persistent = check_temporal_escalation(patient_id, selected_domain, supabase_client)
        if is_persistent:
            resolved_tier = "level_2_diagnostic_investigation"
            action_steps["escalation_reason"] = (
                "Longitudinal Escalation: This physiological anomaly has persisted for over 48 hours without resolution. "
                "Stepping up to at-home diagnostic review."
            )

    # 4. Extract Tier Data
    level_data = escalation_levels.get(resolved_tier, escalation_levels.get("level_1_bedside_triage", {}))

    primary_cta = copy.deepcopy(level_data.get("primary_cta"))
    secondary_cta = copy.deepcopy(level_data.get("secondary_cta"))
    caregiver_checklist = copy.deepcopy(level_data.get("caregiver_checklist", []))

    # Fallbacks if tier data missing
    if not primary_cta:
        primary_cta = {
            "label": "Review my metrics",
            "action": "VIEW_METRICS",
            "icon": "activity"
        }
    if not secondary_cta:
        secondary_cta = {
            "label": "Chat with Health Coach",
            "action": "START_COACH_CHAT",
            "icon": "message-circle"
        }

    # Inject dynamic context if provided
    if context:
        if primary_cta:
            primary_cta["context"] = context
        if secondary_cta:
            secondary_cta["context"] = context

    # 5. Populate Output
    action_steps["primary_cta"] = primary_cta
    action_steps["secondary_cta"] = secondary_cta
    action_steps["caregiver_checklist"] = caregiver_checklist
    action_steps["clinical_domain"] = selected_domain
    action_steps["escalation_tier"] = resolved_tier

    # Clean up internal / temporary selection keys
    action_steps.pop("selected_pathway", None)
    action_steps.pop("selected_domain", None)
    action_steps.pop("escalation_level", None)
    action_steps.pop("intent_key", None)
    action_steps.pop("domain", None)
    action_steps.pop("level", None)

    return action_steps
