-- Add Caregiver Nudge Preference to patients table
ALTER TABLE patients
ADD COLUMN IF NOT EXISTS caregiver_nudge_preference TEXT DEFAULT 'HIGH';

-- Table for Active Clinical Insights (generated by the event-driven Tripwire)
CREATE TABLE IF NOT EXISTS active_clinical_insights (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    patient_id UUID REFERENCES patients(id) ON DELETE CASCADE,
    rule_id TEXT NOT NULL,
    name TEXT NOT NULL,
    severity TEXT NOT NULL,
    category TEXT NOT NULL,
    message TEXT NOT NULL,
    evidence JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    resolved BOOLEAN DEFAULT false
);

-- Table for Daily Morning Briefings (generated by the nightly batch job)
CREATE TABLE IF NOT EXISTS daily_morning_briefings (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    patient_id UUID REFERENCES patients(id) ON DELETE CASCADE,
    summary TEXT,
    schedule JSONB DEFAULT '{}'::jsonb,
    health_context JSONB DEFAULT '{}'::jsonb,
    date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS
ALTER TABLE active_clinical_insights ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_morning_briefings ENABLE ROW LEVEL SECURITY;

-- Simple Policies for service role (Assuming application manages access)
CREATE POLICY "Service Role Full Access for insights" ON active_clinical_insights USING (true) WITH CHECK (true);
CREATE POLICY "Service Role Full Access for briefings" ON daily_morning_briefings USING (true) WITH CHECK (true);
